# Project Title

## News Article Classification Using Natural Language Processing and Machine Learning

# Project Description

This project focuses on building a machine learning model that automatically classifies news articles into different categories using Natural Language Processing (NLP) techniques. With the increasing amount of online news content, organizing and categorizing news articles manually has become difficult and time-consuming.

The system analyzes the text content of news articles and assigns them to predefined categories such as World, Sports, Business, and Technology. NLP techniques are used to preprocess and clean the text data before converting it into numerical features suitable for machine learning models.

Feature extraction is performed using Term Frequency–Inverse Document Frequency (TF-IDF), which measures the importance of words within a document relative to the entire dataset. Machine learning algorithms such as Logistic Regression or Naive Bayes are then used to train a classification model capable of predicting the category of a news article.

The developed system demonstrates how NLP and machine learning techniques can be applied to automatically organize large volumes of textual data in news and media platforms.

# Abstract

With the rapid expansion of digital media and online news platforms, a massive amount of textual information is generated every day. Automatically organizing and categorizing news articles has become essential for efficient information management.

This project presents a news article classification system using Natural Language Processing and Machine Learning techniques. The system is trained using the AG News Dataset, which contains thousands of news articles categorized into four classes: World, Sports, Business, and Technology.

Text preprocessing techniques such as lowercasing, punctuation removal, tokenization, and stopword removal are applied to clean the text data. The processed text is then transformed into numerical features using TF-IDF vectorization.

Machine learning algorithms are trained on these features to build a model that can automatically classify news articles based on their content. The performance of the model is evaluated using metrics such as accuracy, precision, recall, and F1-score.

The proposed system demonstrates an effective and efficient approach for automatic text classification using NLP and machine learning techniques.

# Problem Statement

With the rapid growth of digital media and online news platforms, a massive amount of news articles is generated and published every day. Managing and organizing this large volume of textual information manually has become a challenging and time-consuming task. News agencies and online platforms need efficient methods to categorize articles into specific topics so that users can easily access relevant information.

Traditional manual classification of news articles is inefficient and prone to human error. Therefore, there is a need for an automated system that can analyze the content of news articles and accurately classify them into predefined categories.

The main problem addressed in this project is the automatic classification of news articles into categories such as World, Sports, Business, and Technology using Natural Language Processing and Machine Learning techniques.

By using text preprocessing methods, feature extraction techniques such as TF-IDF, and machine learning algorithms, the system aims to build a model that can effectively identify patterns in textual data and classify news articles with high accuracy.

This automated classification system can help improve content organization, enhance user experience, and support efficient information retrieval in digital news platforms.

# Project Overview
# Objective

The main objective of this project is to build a machine learning model that can automatically classify news articles into predefined categories such as World, Sports, Business, and Technology based on their textual content.

# Dataset

* Dataset used: AG News Dataset

* Download link:
https://www.kaggle.com/datasets/amananandrai/ag-news-classification-dataset

# Dataset contains:

* 127,600 news articles

# Categories:

* World
* Sports
* Business
* Technology

# Dataset columns:

* Column:
    * Class Index (Category label)
    * Title	News headline
    * Description (Description	News summary)

# 1. Data Collection

The AG News dataset is downloaded and loaded into the system using Python libraries such as pandas.

In [1]:
import pandas  as pd

In [2]:
df_train = pd.read_csv('train.csv')
print(df_train.shape)
df_train.head()

(120000, 3)

,Class Index,Title,Description
0,3,Wall St. Bears Claw Back Into the Black (Reuters),"Reuters - Short-sellers, Wall Street's dwindli..."
1,3,Carlyle Looks Toward Commercial Aerospace (Reu...,Reuters - Private investment firm Carlyle Grou...
2,3,Oil and Economy Cloud Stocks' Outlook (Reuters),Reuters - Soaring crude prices plus worries\ab...
3,3,Iraq Halts Oil Exports from Main Southern Pipe...,Reuters - Authorities have halted oil export\f...
4,3,"Oil prices soar to all-time record, posing new...","AFP - Tearaway world oil prices, toppling reco..."

where 
* 1-World, 
* 2-Sports, 
* 3-Business, 
* 4-Sci/Tech

In [3]:
df_train['Class Index'].value_counts()

Class Index
3    30000
4    30000
2    30000
1    30000
Name: count, dtype: int64

In [4]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120000 entries, 0 to 119999
Data columns (total 3 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Class Index  120000 non-null  int64
 1   Title        120000 non-null  object
 2   Description  120000 non-null  object
dtypes: int64(1), object(2)
memory usage: 2.7+ MB

# 2. Text Preprocessing
* Text data is cleaned and prepared using the following steps:
    * Convert text to lowercase
    * Remove punctuation
    * Remove stopwords
    * Tokenize text into words

These steps help improve the performance of machine learning models.

In [5]:
import spacy

In [6]:
nlp = spacy.load("en_core_web_sm")

In [7]:
def preprocess(text):
    doc = nlp(text)
    filtered_tokens = []
    for token in doc:
        if token.is_stop or token.is_punct:
            continue
        filtered_tokens.append(token.lemma_)
    
    return " ".join(filtered_tokens)

In [8]:
df_train['Preprocess_Title'] = df_train['Title'].apply(preprocess)

In [9]:
df_train['Preprocess_Description'] = df_train['Description'].apply(preprocess)

In [10]:
df_train.head()

,Class Index,Title,Description,Preprocess_Title,Preprocess_Description
0,3,Wall St. Bears Claw Back Into the Black (Reuters),"Reuters - Short-sellers, Wall Street's dwindli...",Wall St. Bears Claw Black Reuters,Reuters short seller Wall Street dwindling\ban...
1,3,Carlyle Looks Toward Commercial Aerospace (Reu...,Reuters - Private investment firm Carlyle Grou...,Carlyle look Commercial Aerospace Reuters,"reuters private investment firm Carlyle Group,..."
2,3,Oil and Economy Cloud Stocks' Outlook (Reuters),Reuters - Soaring crude prices plus worries\ab...,oil Economy Cloud Stocks Outlook Reuters,Reuters soar crude price plus worries\about ec...
3,3,Iraq Halts Oil Exports from Main Southern Pipe...,Reuters - Authorities have halted oil export\f...,Iraq Halts Oil Exports Main Southern Pipeline ...,Reuters Authorities halt oil export\flows main...
4,3,"Oil prices soar to all-time record, posing new...","AFP - Tearaway world oil prices, toppling reco...",oil price soar time record pose new menace eco...,AFP Tearaway world oil price topple record str...

In [11]:
df_train['combined_text'] = df_train['Preprocess_Title'] + " " + df_train['Preprocess_Description']

In [12]:
df_train.head()

,Class Index,Title,Description,Preprocess_Title,Preprocess_Description,combined_text
0,3,Wall St. Bears Claw Back Into the Black (Reuters),"Reuters - Short-sellers, Wall Street's dwindli...",Wall St. Bears Claw Black Reuters,Reuters short seller Wall Street dwindling\ban...,Wall St. Bears Claw Black Reuters Reuters shor...
1,3,Carlyle Looks Toward Commercial Aerospace (Reu...,Reuters - Private investment firm Carlyle Grou...,Carlyle look Commercial Aerospace Reuters,"reuters private investment firm Carlyle Group,...",Carlyle look Commercial Aerospace Reuters reut...
2,3,Oil and Economy Cloud Stocks' Outlook (Reuters),Reuters - Soaring crude prices plus worries\ab...,oil Economy Cloud Stocks Outlook Reuters,Reuters soar crude price plus worries\about ec...,oil Economy Cloud Stocks Outlook Reuters Reute...
3,3,Iraq Halts Oil Exports from Main Southern Pipe...,Reuters - Authorities have halted oil export\f...,Iraq Halts Oil Exports Main Southern Pipeline ...,Reuters Authorities halt oil export\flows main...,Iraq Halts Oil Exports Main Southern Pipeline ...
4,3,"Oil prices soar to all-time record, posing new...","AFP - Tearaway world oil prices, toppling reco...",oil price soar time record pose new menace eco...,AFP Tearaway world oil price topple record str...,oil price soar time record pose new menace eco...

# 3. Feature Extraction
* The cleaned text data is converted into numerical form using TF-IDF Vectorization, which measures the importance of words in the dataset.

In [13]:
X = df_train['combined_text']
y = df_train['Class Index']

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

# 4. Model Training

Machine learning algorithms are used to train the classification model.

Algorithms used:

* Logistic Regression

* KNN Model

* Naive Bayes

* Decision Tree Classifier

* Linear Support Vector Machine

These algorithms learn patterns from the dataset and classify news articles into their respective categories.

# Logistic Regression

In [16]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline

clf_LR = Pipeline([
    ("vectorizer",TfidfVectorizer()),
    ("Logistic Regression",LogisticRegression(max_iter=2000))
])

In [17]:
clf_LR.fit(X_train,y_train)

Pipeline(steps=[('vectorizer', TfidfVectorizer()),
                ('Logistic Regression', LogisticRegression(max_iter=2000))])

In [18]:
y_pred_LR = clf_LR.predict(X_test)

In [19]:
from sklearn.metrics import classification_report

In [20]:
print(classification_report(y_test,y_pred_LR))

              precision    recall  f1-score   support

           1       0.93      0.90      0.92      5956
           2       0.95      0.98      0.97      6058
           3       0.88      0.89      0.89      5911
           4       0.90      0.89      0.90      6075

    accuracy                           0.92     24000
   macro avg       0.92      0.92      0.92     24000
weighted avg       0.92      0.92      0.92     24000

In [21]:
new_sentence = ["Apple launches new AI powered iPhone"]

prediction = clf_LR.predict(new_sentence)

print(prediction)

[4]

# KNN Model

In [22]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.neighbors import KNeighborsClassifier
from sklearn.pipeline import Pipeline

clf_KNN = Pipeline([
    ("vectorizer",TfidfVectorizer()),
    ("KNN",KNeighborsClassifier())
])

In [23]:
clf_KNN.fit(X_train,y_train)

Pipeline(steps=[('vectorizer', TfidfVectorizer()),
                ('KNN', KNeighborsClassifier())])

In [24]:
y_pred_KNN = clf_KNN.predict(X_test)

In [25]:
print(classification_report(y_test,y_pred_KNN))

              precision    recall  f1-score   support

           1       0.91      0.89      0.90      5956
           2       0.94      0.97      0.95      6058
           3       0.86      0.88      0.87      5911
           4       0.90      0.87      0.88      6075

    accuracy                           0.90     24000
   macro avg       0.90      0.90      0.90     24000
weighted avg       0.90      0.90      0.90     24000

In [26]:
new_sentence = ["Apple launches new AI powered iPhone"]

prediction = clf_KNN.predict(new_sentence)

print(prediction)

[4]

# Multinomial Naive Bayes

In [27]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline

clf_NB = Pipeline([
    ("vectorizer",TfidfVectorizer()),
    ("NB",MultinomialNB())
])

In [28]:
clf_NB.fit(X_train,y_train)

Pipeline(steps=[('vectorizer', TfidfVectorizer()), ('NB', MultinomialNB())])

In [29]:
y_pred_NB = clf_NB.predict(X_test)

In [30]:
print(classification_report(y_test,y_pred_NB))

              precision    recall  f1-score   support

           1       0.92      0.89      0.91      5956
           2       0.95      0.98      0.96      6058
           3       0.86      0.88      0.87      5911
           4       0.89      0.87      0.88      6075

    accuracy                           0.91     24000
   macro avg       0.91      0.91      0.91     24000
weighted avg       0.91      0.91      0.91     24000

# Decision tree classifier

In [31]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.tree import DecisionTreeClassifier 
from sklearn.pipeline import Pipeline

clf_tree = Pipeline([
    ("vectorizer",TfidfVectorizer()),
    ("KNN",DecisionTreeClassifier())
])

In [32]:
clf_tree.fit(X_train,y_train)

Pipeline(steps=[('vectorizer', TfidfVectorizer()),
                ('KNN', DecisionTreeClassifier())])

In [33]:
y_pred_tree = clf_tree.predict(X_test)

In [34]:
print(classification_report(y_test,y_pred_tree))

              precision    recall  f1-score   support

           1       0.81      0.82      0.81      5956
           2       0.87      0.89      0.88      6058
           3       0.76      0.77      0.77      5911
           4       0.79      0.77      0.78      6075

    accuracy                           0.81     24000
   macro avg       0.81      0.81      0.81     24000
weighted avg       0.81      0.81      0.81     24000

# Support vector machine Model

In [35]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import LinearSVC 
from sklearn.pipeline import Pipeline

clf_SVC = Pipeline([
    ("vectorizer",TfidfVectorizer()),
    ("SVC",LinearSVC())
])

In [36]:
clf_SVC.fit(X_train,y_train)

Pipeline(steps=[('vectorizer', TfidfVectorizer()), ('SVC', LinearSVC())])

In [37]:
y_pred_svc = clf_SVC.predict(X_test)

In [38]:
print(classification_report(y_test,y_pred_svc))

              precision    recall  f1-score   support

           1       0.93      0.90      0.91      5956
           2       0.96      0.98      0.97      6058
           3       0.88      0.89      0.89      5911
           4       0.90      0.89      0.90      6075

    accuracy                           0.92     24000
   macro avg       0.92      0.92      0.92     24000
weighted avg       0.92      0.92      0.92     24000

# Save the Model

In [40]:
import joblib

In [41]:
joblib.dump(clf_LR,"News_Classificatiom_Model_LR.joblib")

['News_Classificatiom_Model_LR.joblib']

5. Model Evaluation

The trained model is evaluated using the following metrics:

Accuracy

Precision

Recall

F1 Score

These metrics help measure how well the model performs in classifying news articles.

Expected Outcome

The expected outcomes of this project include:

Automatic classification of news articles into categories

Efficient organization of large text datasets

Achieving classification accuracy of approximately 88–92%

Demonstrating the application of NLP and machine learning for text classification tasks